presto:
  sources: 
    mysql1:
      url: jdbc:url
      user: username
      password: pwd
      jar-location: url # can be hosted in a cdn/localy and will be fetched and uploaded into the system
      tables: ["o_source","s_source"]
    mysql2:
      url: jdbc:url
      user: username
      password: pwd
      jar-location: url # can be hosted in a cdn/localy and will be fetched and uploaded into the system
      tables: ["ps_source"]
    pg1:
      url: jdbc:url
      user: username
      password: pwd
      jar-location: url
      tables: ["li_source"]
    pg2:
      url: jdbc:url
      user: username
      password: pwd
      jar-location: url
      tables: ["pa_source","r_source"]
    pg3:
      url: jdbc:url
      user: username
      password: pwd
      jar-location: url
      tables: ["c_source","n_source"]
  queries: ["q1:q11","d1","d3"]
  metrics: ["processing time", "rows/sec"]
  scale_factors: [sf1,sf10]
drill:
  sources: 
    mysql:
      url: jdbc:url
      user: username
      password: pwd
      jar-location: url # can be hosted in a cdn/localy and will be fetched and uploaded into the system
      tables: ["li_source","s_source"]
    postgress:
      url: jdbc:url
      user: username
      password: pwd
      jar-location: url
      tables: ["n_source","r_source","s_source"]
  queries: ["q1","q2"] # or ["q1:q7"]
  metrics: ["processing time", "rows/sec"]
  scale_factors: sf1
spark:
  sources: 
    mysql:
      url: jdbc:url
      user: username
      password: pwd
      jar-location: url # can be hosted in a cdn/localy and will be fetched and uploaded into the system
      tables: ["li_source","s_source"]
    postgress:
      url: jdbc:url
      user: username
      password: pwd
      jar-location: url
      tables: ["n_source","r_source","s_source"]
  queries: ["q1","q2"] # or ["q1:q7"]
  metrics: ["processing time", "rows/sec"]
  scale_factors: sf1
hive:
  sources: 
    mysql:
      url: jdbc:url
      user: username
      password: pwd
      jar-location: url # can be hosted in a cdn/localy and will be fetched and uploaded into the system
      tables: ["li_source","s_source"]
    postgress:
      url: jdbc:url
      user: username
      password: pwd
      jar-location: url
      tables: ["n_source","r_source","s_source"]
  queries: ["q1","q2"] # or ["q1:q7"]
  metrics: ["processing time", "rows/sec"]
  scale_factors: sf1