version: "3.7"

services:
    jupyter:
        image: jupyter
        container_name: jupyter
        ports: 
        - "8888:8888"
        volumes:
        - ./benchmark/:/home/jovyan/
        command: start-notebook.sh --NotebookApp.password='sha1:2017f6d8a65d:4f2115202d4cd8c081f1c135bc2b41292bcb4ec4'


networks:
  default:
    name: polydb-net